# Preload the image asset into memory (use absolute paths or ~)
preload = ~/.modules/hyprpaper/6.jpg

# Set the wallpaper on a specific monitor
# Leave the monitor name empty (e.g., ",/path/...") to apply to all monitors
wallpaper {
	monitor = eDP-1
	path = ~/.modules/hyprpaper/6.jpg
	fit_mode = cover
}

# Optional settings
splash = false
ipc = true

